module.exports = {
  rest: "rest",
  restIndex: "restIndex",
  restAip: "restAip",
  restCarl: "restCarl",
  rootStatic: "rootStatic",
  swaggerUi: "swaggerUi",
  doc: "doc",
  static: "static",
  staticRes: "staticRes",
  mapping: "staticMapping",
  client: "client",
  clientLite: "clientLite",
  dist: "dist",
  temp: "temp",
  logs: "logs",
  views: "views",
};